### ISSUE TITLE
Add dataset extent REST endpoint

### ISSUE THREAD

**Issue by DenisCarriere** [DenisCarriere/mobile-map-builder#1]
Using `concaveman` should be easy enough to create a polygon of the datasets.

https://github.com/mapbox/concaveman

![image](https://cloud.githubusercontent.com/assets/550895/18295939/a907c168-7473-11e6-9b33-6628b476218c.png)

Proposed endoint:

`/<dataset>/extent(.geojson|.json|.osm)`
`/gatineau-fire-hydrants/extent.geojson`

**Comment by DenisCarriere** [comment]
@james2432 Try it out for a spin, I've got it working now:

Only works for Point datasets for now.

https://addxy.com/gatineau-fire-hydrants/extent.geojson

![image](https://cloud.githubusercontent.com/assets/550895/18300096/1c3f291c-7494-11e6-96ff-b719354cfbe3.png)

**Comment by james2432** [comment]
very nice: 
![extent](https://cloud.githubusercontent.com/assets/498547/18307683/6fb2aee0-74bf-11e6-9879-ae9d1d5c203d.PNG)

**Comment by james2432** [comment]
also shouldn't be hard to "convert" polygons to a point only db as ways and relations just connect multiple points together

**Comment by DenisCarriere** [comment]
No it shouldn't be too hard, I'll let you know when it works with polygons
